### ISSUE TITLE
Build input "hspec-discovery" does not exist

### ISSUE THREAD

**Issue by peti** [skedgeme/wrecker#1]
This project specifies a dependency on `hspec-discovery` at https://github.com/skedgeme/wrecker/blob/master/wrecker.cabal#L75, but that package does not exist on Hackage: http://hackage.haskell.org/package/hspec-discovery.

**Comment by eborden** [comment]
Yes, this should be `hspec-discover`.

**Comment by jfischoff** [comment]
Additionally the tests are unimplemented ... I am working on that currently
... will be done before an announcement.

[image: skedge.me] https://htmlsig.com/t/0000001BJR62J

Jonathan Fischoff / VP of Engineering
jonathan.fischoff@skedge.me / 828.280.5323

skedge.me
600 Madison Ave. 11th floorNYC 10022
http://skedge.me https://htmlsig.com/t/0000001BJR62J

[image: Twitter]  https://htmlsig.com/t/0000001BFZEFZ [image: LinkedIn]
https://htmlsig.com/t/0000001BNE624

**Comment by peti** [comment]
Well, it would be great if the latest Hackage release if this package would not be broken.
