### ISSUE TITLE
Taking over this repo

### ISSUE THREAD

**Issue by lorenzo** [skedgeme/wrecker#9]
Hey, I've been using wrecker for a while and I really like it as I think it has a lot of potential.

I've been slowly adding a few features to my fork and have also built a web interface for it as a separate package. I'd like to make all that public, but it looks to me that this repo is not being watched by any maintainers.

Would it be possible to get ownership of it or maybe be made a contributor?

**Comment by lorenzo** [comment]
@jfischoff sorry for mentioning you directly, but I know you were a past contributor to this repo and I saw you were active and thought you might have an idea about this

**Comment by jfischoff** [comment]
I don't think this is being actively maintained by skedge anymore. I'm happy to
do what I can to help you maintain it.

**Comment by lorenzo** [comment]
I cleaned up the work I was doing in secret and pushed all the improvements I made to my fork:

* Re-implemented the Statistics using a `tdigest`, this allows to calculate percentiles in the stats with fixed memory consumption
* Added a `record-query` options to the CLI: randomising the query string is a common thing to do, and sometimes you are not interest in every single URL, just the path is important
* Added an option to lost the tests that are present in the executable
* Made it compile with stack's lts-9.0
* Used `hindent`, as I'm lazy about having my own formatting standard.

@jfischoff Do you think you could give me maintainer access to hackage so I can push new package versions? 

Otherwise, the alternative would be to publish my fork under another name, which would be a bit sad.

**Comment by jfischoff** [comment]
What is your username on Hackage?

**Comment by jfischoff** [comment]
BTW `TDigest` looks dope.

It would be nice to be able to measure the stages of the request, like connection time and download time. The parsing overhead of `http-client` is large, having these details would make `wrecker` more accurate. This would require patches to `http-client` however.

**Comment by lorenzo** [comment]
@jfischoff my hackage name is `lorenzo`

It sounds like a good idea to account for the library overhead and also track connection + download time, but I'm not sure how much effort that is patch http-client to do that.

**Comment by jfischoff** [comment]
The other options is to move to `uhttpc` which I think would be more likely to accept those sort of patches. I'll add you shortly.

**Comment by jfischoff** [comment]
@lorenzo I've added you as a maintainer. Thanks!

**Comment by lorenzo** [comment]
Thanks @jfischoff 

I'll look into `uhttpc` too
